//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;
using System;

[assembly: AssemblyTitle("Cake.Twitter")]
[assembly: AssemblyDescription("Cake Twitter AddIn")]
[assembly: AssemblyCompany("Cake Contributions")]
[assembly: AssemblyProduct("Cake.Twitter")]
[assembly: AssemblyVersion("0.1.0")]
[assembly: AssemblyFileVersion("0.1.0")]
[assembly: AssemblyInformationalVersion("0.1.0")]
[assembly: AssemblyCopyright("Copyright © Cake Contributions 2016 - Present")]
[assembly: CLSCompliant(true)]